name: functional_widget_annotation_example
description: A new Flutter project.
environment:
  sdk: ^2.5.0

dependencies:
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.5.1

dev_dependencies:
  build_runner: ^1.9.0
  functional_widget:
    path: ../../functional_widget
