name: functional_widget_example
description: A new Flutter project.
environment:
  sdk: ^2.5.0

dependencies:
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.5.1

builders:
  functional_widget: ^0.7.2
